### PR TITLE
Have to decode the object before you json.loads it.

### PR DESCRIPTION
**Pull request by tebriel**
`res` is bytes until you `decode` it.

### CODE REVIEW

**Comment by tebriel** [comment]
Also meets pep8 now.

**Comment by pthrasher** [comment]
This works in python 2, and I know @tebriel tested his in python 3. I'm sitting across from him, heh.

**Comment by kingsawyer** [comment]
Hi Chris,
Awesome! Thanks. I did the Python 3 changes when the server was down so I
missed this. However I found independently that just plain decode broke
2.x. I'll get the pep8 in.
-Dave

**Comment by tebriel** [comment]
Okay cool. Glad I could be of any kind of help.

**Comment by kingsawyer** [comment]
Hi Chris,

We're having an open space tonight after dinner (8:00pm) to accelerate
people's solutions and I'd like to invite you to join us either to make
your own solution and get a copper mule cup or to help others write awesome
Python code.

-Dave

**Comment by tebriel** [comment]
Definitely. I'll bring my friend @pthrasher and we'll help others and finish development our own solutions. Where are we meeting? Just in front of the Box Booth?

On April 11, 2015 at 2:49:23 PM, Dave Sawyer (notifications@github.commailto:notifications@github.com) wrote:

Hi Chris,

We're having an open space tonight after dinner (8:00pm) to accelerate
people's solutions and I'd like to invite you to join us either to make
your own solution and get a copper mule cup or to help others write awesome
Python code.

-Dave

**Comment by kingsawyer** [comment]
We're in the open spaces 510D

**Comment by tebriel** [comment]
Grabbing food. Be there in a bit.

On Sat, Apr 11, 2015 at 5:54 PM -0700, "Dave Sawyer" <notifications@github.com<mailto:notifications@github.com>> wrote:

We're in the open spaces 510D

**Pull request closed without merging**
